export type UiProps = {
  commandToDelete: any,
  commandToEdit: any,
  deleteCommand: any,
  deleteCommandConfirm: any,
  editCommand: any,
  filteredCommands: any,
  isAddModalOpen: any,
  isDeleteModalOpen: any,
  isEditModalOpen: any,
  saveCommand: any,
  searchBoxRef: any,
  searchText: any,
  setCommandToEdit: any,
  setIsAddModalOpen: any,
  setIsDeleteModalOpen: any,
  setIsEditModalOpen: any,
  setSearchText: any,
  updateCommand: any,
} 